import React, { useState, useEffect } from 'react';

const PIPELINE_STAGES = [
  {
    id: 1,
    title: "Payload Ingestion",
    icon: "input",
    description: "Captures raw incoming data from the Chrome Extension context menus and content scripts.",
    details: [
      { label: "Data Types", value: "Raw URLs, DOM Content, EML Headers, Raw Body Text" },
      { label: "Preprocessing", value: "Lowercasing, HTML stripping, URL/Email tokenization" },
      { label: "Sanitization", value: "Regex filtering to remove noise and extract base domains" }
    ],
    codeSnippet: "combined_text = f\"{subject} {body}\".strip()\ncleaned_text = clean_email_text(combined_text)"
  },
  {
    id: 2,
    title: "Feature Extraction",
    icon: "data_object",
    description: "Transforms raw text and URLs into structured mathematical vectors for machine learning.",
    details: [
      { label: "URL Vectors", value: "Extracts 30 specific features (Length, @ symbols, WHOIS age, HTTPS)" },
      { label: "NLP Vectors", value: "TF-IDF (Term Frequency-Inverse Document Frequency) vectorization" },
      { label: "DOM Parsing", value: "BeautifulSoup extraction of hidden iframes and external form handlers" }
    ],
    codeSnippet: "vector = [features.get(f, 0) for f in URL_FEATURE_ORDER]\nX = np.array([vector], dtype=float)"
  },
  {
    id: 3,
    title: "ML Classification",
    icon: "model_training",
    description: "Trained XGBoost models evaluate the extracted vectors against historical phishing datasets.",
    details: [
      { label: "Model Type", value: "XGBoost (Extreme Gradient Boosting) Decision Trees" },
      { label: "Confidence", value: "Outputs a raw probability score between 0.0 and 1.0" },
      { label: "Explainability", value: "SHAP (SHapley Additive exPlanations) values for top driving features" }
    ],
    codeSnippet: "proba = email_model.predict_proba([cleaned_text])[0]\nml_phish_prob = float(proba[phish_idx])"
  },
  {
    id: 4,
    title: "Context & Behavior Engine",
    icon: "psychology_alt",
    description: "Heuristic rule engines analyze the psychological intent and technical behavior of the payload.",
    details: [
      { label: "Behavior", value: "Follows redirect chains to uncover hidden malicious destinations" },
      { label: "Urgency Intent", value: "Detects coercive language ('urgent', 'suspended', '24 hours')" },
      { label: "Impersonation", value: "Cross-references sender domains against Top Brands (PayPal, Microsoft)" }
    ],
    codeSnippet: "if any(word in combined_text.lower() for word in FINANCIAL_KEYWORDS):\n    score += 15"
  },
  {
    id: 5,
    title: "AI Fingerprinting",
    icon: "memory",
    description: "Detects if the phishing lure was generated by a Large Language Model (e.g., ChatGPT).",
    details: [
      { label: "Perplexity", value: "Measures the unpredictability of word choices" },
      { label: "Burstiness", value: "Analyzes sentence length variance (AI tends to be highly uniform)" },
      { label: "Formality", value: "Detects unnatural absence of contractions and overly polite phrasing" }
    ],
    codeSnippet: "ai_result = analyze_ai_fingerprint(body)\nai_score = ai_result['ai_score']"
  },
  {
    id: 6,
    title: "Master Fusion Engine",
    icon: "hub",
    description: "Combines scores from all sub-engines using a weighted ensemble to produce the final verdict.",
    details: [
      { label: "ML Weight", value: "30% (Email Content) / 25% (URL Structure)" },
      { label: "Context Weight", value: "15% (Urgency, Impersonation)" },
      { label: "Behavior Weight", value: "20% (Redirects, Action verbs)" },
      { label: "AI/Attachment", value: "10% each (Generative patterns, Sandboxing)" }
    ],
    codeSnippet: "final_risk_score = (ml * 0.3) + (url * 0.25) + (ctx * 0.15) + (beh * 0.20) + (ai * 0.10)"
  }
];

const PipelineOverview = () => {
  const [activeStage, setActiveStage] = useState(1);
  const [isSimulating, setIsSimulating] = useState(false);

  // Auto-advance simulation logic
  useEffect(() => {
    let interval;
    if (isSimulating) {
      interval = setInterval(() => {
        setActiveStage((prev) => {
          if (prev === 6) {
            setIsSimulating(false);
            return 6;
          }
          return prev + 1;
        });
      }, 1500); // 1.5 seconds per stage
    }
    return () => clearInterval(interval);
  }, [isSimulating]);

  const handleSimulate = () => {
    setActiveStage(1);
    setIsSimulating(true);
  };

  const currentStageData = PIPELINE_STAGES.find(s => s.id === activeStage);

  return (
    <div className="p-8 space-y-8 w-full min-h-[calc(100vh-100px)] flex flex-col">

      {/* Header */}
      <div className="flex justify-between items-end border-b border-[#76767f]/20 pb-6">
        <div>
          <h2 className="text-3xl font-black text-white tracking-tight" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
            Threat Detection Pipeline
          </h2>
          <p className="text-[#76767f] text-sm mt-2" style={{ fontFamily: 'Plus Jakarta Sans, sans-serif' }}>
            Interactive visualization of the SafePhish multi-engine architecture.
          </p>
        </div>
        <button
          onClick={handleSimulate}
          disabled={isSimulating}
          className={`flex items-center gap-2 px-6 py-2.5 rounded-lg font-bold text-sm tracking-wide uppercase transition-all
            ${isSimulating ? 'bg-[#76767f]/20 text-[#76767f] cursor-not-allowed' : 'bg-emerald-600 text-white hover:bg-emerald-500 shadow-[0_0_15px_rgba(16,185,129,0.3)]'}`}
          style={{ fontFamily: 'Plus Jakarta Sans, sans-serif' }}
        >
          <span className="material-symbols-outlined text-[18px]">
            {isSimulating ? 'sync' : 'play_arrow'}
          </span>
          {isSimulating ? 'Simulating Flow...' : 'Run Simulation'}
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 flex-1">

        {/* Left Column: The Pipeline Timeline */}
        <div className="lg:col-span-4 bg-[#76767f]/5 border border-[#76767f]/20 rounded-xl p-6 relative">
          <div className="absolute left-10 top-10 bottom-10 w-0.5 bg-[#76767f]/20 z-0"></div>

          <div className="space-y-6 relative z-10">
            {PIPELINE_STAGES.map((stage) => {
              const isActive = activeStage === stage.id;
              const isPast = activeStage > stage.id;

              return (
                <button
                  key={stage.id}
                  onClick={() => { setIsSimulating(false); setActiveStage(stage.id); }}
                  className={`w-full flex items-center gap-4 p-3 rounded-lg transition-all text-left group
                    ${isActive ? 'bg-[#060819] border border-[#aab3d8]/50 shadow-[0_0_15px_rgba(170,179,216,0.1)]' : 'hover:bg-[#76767f]/10 border border-transparent'}`}
                >
                  <div className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 transition-colors
                    ${isActive ? 'bg-[#aab3d8] text-[#060819] shadow-[0_0_10px_rgba(170,179,216,0.5)]' :
                      isPast ? 'bg-emerald-500/20 text-emerald-500 border border-emerald-500/50' :
                        'bg-[#060819] border border-[#76767f]/30 text-[#76767f]'}`}
                  >
                    <span className="material-symbols-outlined text-[16px]">
                      {isPast ? 'check' : stage.icon}
                    </span>
                  </div>
                  <div>
                    <h4 className={`text-sm font-bold ${isActive ? 'text-white' : 'text-[#aab3d8]'}`} style={{ fontFamily: 'Plus Jakarta Sans, sans-serif' }}>
                      Stage 0{stage.id}
                    </h4>
                    <p className={`text-xs ${isActive ? 'text-[#aab3d8]' : 'text-[#76767f] group-hover:text-[#aab3d8]/70'}`}>
                      {stage.title}
                    </p>
                  </div>
                </button>
              );
            })}
          </div>
        </div>

        {/* Right Column: Engine Inspector */}
        <div className="lg:col-span-8 flex flex-col gap-6">

          {/* Active Stage Details */}
          <div className="bg-[#060819] border border-[#76767f]/20 rounded-xl p-8 flex-1 relative overflow-hidden">
            {/* Background decoration */}
            <span className="material-symbols-outlined absolute -bottom-10 -right-10 text-[250px] text-[#76767f]/5 select-none pointer-events-none" style={{ fontVariationSettings: "'FILL' 1" }}>
              {currentStageData.icon}
            </span>

            <div className="relative z-10 space-y-8">
              <div className="flex items-start gap-4">
                <div className="bg-[#aab3d8]/10 p-3 rounded-xl border border-[#aab3d8]/20">
                  <span className="material-symbols-outlined text-4xl text-[#aab3d8]">{currentStageData.icon}</span>
                </div>
                <div>
                  <div className="text-[10px] text-[#76767f] font-bold uppercase tracking-widest mb-1" style={{ fontFamily: 'Plus Jakarta Sans, sans-serif' }}>
                    Engine Inspector • Stage 0{currentStageData.id}
                  </div>
                  <h3 className="text-3xl font-black text-white" style={{ fontFamily: 'Space Grotesk, sans-serif' }}>
                    {currentStageData.title}
                  </h3>
                  <p className="text-[#aab3d8] mt-2 text-sm leading-relaxed max-w-2xl">
                    {currentStageData.description}
                  </p>
                </div>
              </div>

              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {currentStageData.details.map((detail, idx) => (
                  <div key={idx} className="bg-[#76767f]/10 p-4 rounded-lg border border-[#76767f]/20">
                    <div className="text-[#aab3d8] font-bold text-xs uppercase tracking-wider mb-2" style={{ fontFamily: 'Plus Jakarta Sans, sans-serif' }}>
                      {detail.label}
                    </div>
                    <div className="text-[#76767f] text-xs leading-relaxed">
                      {detail.value}
                    </div>
                  </div>
                ))}
              </div>

              <div className="bg-[#12131a] rounded-lg border border-[#76767f]/30 overflow-hidden">
                <div className="bg-[#76767f]/10 px-4 py-2 border-b border-[#76767f]/30 flex items-center gap-2">
                  <span className="w-2.5 h-2.5 rounded-full bg-red-500"></span>
                  <span className="w-2.5 h-2.5 rounded-full bg-yellow-500"></span>
                  <span className="w-2.5 h-2.5 rounded-full bg-green-500"></span>
                  <span className="ml-2 text-[10px] text-[#76767f] font-mono uppercase tracking-widest">server.py</span>
                </div>
                <pre className="p-4 overflow-x-auto">
                  <code className="text-[#aab3d8] text-[11px] font-mono leading-relaxed">
                    {currentStageData.codeSnippet}
                  </code>
                </pre>
              </div>
            </div>
          </div>

          {/* Bottom Simulated Output Console */}
          <div className="bg-[#0c0e15] border border-[#76767f]/20 rounded-xl p-4 h-32 flex flex-col justify-end relative overflow-hidden">
            <div className="absolute top-0 left-0 w-full h-full bg-gradient-to-b from-[#0c0e15] to-transparent z-0"></div>

            <div className="relative z-10 font-mono text-[10px] space-y-1.5 flex flex-col justify-end h-full">
              {activeStage > 1 && <div className="text-[#76767f] opacity-50">[{new Date().toISOString()}] INFO: Engine {activeStage - 1} completed successfully.</div>}
              <div className="text-emerald-500 animate-pulse">
                [{new Date().toISOString()}] SYSTEM: Initializing {currentStageData.title}...
              </div>
              <div className="text-[#aab3d8]">
                &gt; Processing payload through {currentStageData.title.toLowerCase().split(' ')[0]} heuristics...
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  );
};

export default PipelineOverview;